//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackIt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bank
    {
        public Bank()
        {
            this.BankAddresses = new HashSet<BankAddress>();
            this.PersonBanks = new HashSet<PersonBank>();
        }
    
        public int BankId { get; set; }
        public string BankName { get; set; }
        public string RoutingCode { get; set; }
        public string AccountNumber { get; set; }
        public string SwiftCode { get; set; }
        public Nullable<int> AddressId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> IsDeletedByDate { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual ICollection<BankAddress> BankAddresses { get; set; }
        public virtual ICollection<PersonBank> PersonBanks { get; set; }
    }
}
