//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackIt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankAddress
    {
        public int BankAddressId { get; set; }
        public Nullable<int> BankId { get; set; }
        public Nullable<int> AddressId { get; set; }
        public Nullable<bool> IsPrimary { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Bank Bank { get; set; }
        public virtual Bank Bank1 { get; set; }
    }
}
