//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackIt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bank
    {
        public int BankId { get; set; }
        public string BankName { get; set; }
        public string RoutingCode { get; set; }
        public string AccountNumber { get; set; }
        public string SwiftCode { get; set; }
        public Nullable<int> AddressId { get; set; }
    }
}
