//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackIt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int PaymentId { get; set; }
        public int RecipientId { get; set; }
        public Nullable<int> PersonBankId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Description { get; set; }
        public string CheckNumber { get; set; }
        public Nullable<int> CheckedSignedById { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
        public Nullable<int> PaymentSentBy { get; set; }
        public Nullable<int> PaymentById { get; set; }
        public Nullable<bool> IsCleared { get; set; }
        public Nullable<System.DateTime> IsClearedDate { get; set; }
        public Nullable<int> IsAcknowledged { get; set; }
        public Nullable<System.DateTime> IsAcknowledgedDate { get; set; }
        public string Notes { get; set; }
        public Nullable<int> CreatedByUserId { get; set; }
        public Nullable<System.DateTime> CreatedByDate { get; set; }
        public Nullable<int> UpdatedByUserId { get; set; }
        public Nullable<System.DateTime> UpdatedByDate { get; set; }
        public Nullable<int> DeletedByUserId { get; set; }
        public Nullable<System.DateTime> DeletedByDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual PersonBank PersonBank { get; set; }
        public virtual Person Person { get; set; }
    }
}
