//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackIt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonOrganization
    {
        public PersonOrganization()
        {
            this.People = new HashSet<Person>();
        }
    
        public int PersonOrganizationId { get; set; }
        public Nullable<int> PersonId { get; set; }
        public Nullable<int> OrganizationId { get; set; }
        public Nullable<bool> IsPrimary { get; set; }
    
        public virtual Organization Organization { get; set; }
        public virtual ICollection<Person> People { get; set; }
        public virtual Person Person { get; set; }
    }
}
