//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackIt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonBank
    {
        public PersonBank()
        {
            this.Payments = new HashSet<Payment>();
            this.People = new HashSet<Person>();
        }
    
        public int PersonBankId { get; set; }
        public int PersonId { get; set; }
        public int BankId { get; set; }
        public Nullable<bool> IsPrimaryBank { get; set; }
    
        public virtual Bank Bank { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual ICollection<Person> People { get; set; }
        public virtual Person Person { get; set; }
    }
}
