//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackIt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public int PersonId { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string DisplayName { get; set; }
        public string AlternateName { get; set; }
        public string Title { get; set; }
        public string Position { get; set; }
        public string Role { get; set; }
        public string Notes { get; set; }
        public Nullable<int> PrimaryContactId { get; set; }
        public Nullable<int> ContactDetailsId { get; set; }
        public Nullable<int> PrimaryBankId { get; set; }
        public Nullable<int> BankDetailsId { get; set; }
        public Nullable<int> OrganizationsId { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public Nullable<System.DateTime> CreatedByDate { get; set; }
        public Nullable<int> UpdatedById { get; set; }
        public Nullable<System.DateTime> UpdatedByDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedByDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
